name: Run Bot 2 Every 2 Hours (Ganjil)

on:
  schedule:
    - cron: '0 1-23/2 * * *' # Berjalan setiap kelipatan 2 jam di jam ganjil
  workflow_dispatch:

jobs:
  run-bot2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot 2
        run: python bot2.py
