name: Run Bot 1 Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *' # Berjalan setiap kelipatan 2 jam (Genap)
  workflow_dispatch:

jobs:
  run-bot1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot 1
        run: python bot.py
